VIA_ENABLE = yes
# VIAL_ENABLE = yes
LTO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = yes
# QMK_SETTINGS = no
# TAP_DANCE_ENABLE = no
# KEY_OVERRIDE_ENABLE = no

CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
# COMBO_ENABLE = no
